##NumPy
`NumPy` — библиотека с открытым исходным кодом для языка программирования Python. Возможности:

*   поддержка многомерных массивов (включая матрицы);
*   поддержка высокоуровневых математических функций, предназначенных для работы с многомерными массивами.

(Сообщает нам википедия.)

[На хабре](https://habr.com/ru/post/352678/) можно почитать статью с ещё большим количеством примеров, чем приведу я. 

In [9]:
import numpy as np
import pandas as pd

In [10]:
data = pd.read_csv('virus_data.csv'),

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (1,2,10,11,13,14,15,16,17,18,19,20,22,23,24,25,26,27,31,32) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [11]:
data.head()

ID    age     sex              city          province        country  \
0  000-1-  30-39  female  Snohomish County        Washington  United States   
1  000-1-    NaN     NaN               NaN         Khuzestan           Iran   
2  000-1-    NaN     NaN               NaN               NaN            NaN   
3  000-1-  50-59    male  Snohomish County        Washington  United States   
4  000-1-    NaN     NaN               NaN  Pays de la Loire         France   

   wuhan(0)_not_wuhan(1)   latitude   longitude geo_resolution  ...  \
0                    1.0  48.048180 -121.696000         admin2  ...   
1                    1.0  31.496225   48.967279         admin1  ...   
2                    NaN        NaN         NaN            NaN  ...   
3                    1.0  48.048180 -121.696000         admin2  ...   
4                    1.0  47.486460   -0.811280         admin1  ...   

  date_death_or_discharge notes_for_discussion location admin3  \
0                     NaN                  NaN      NaN    NaN   
1                     NaN                  NaN      NaN    NaN   
2                     NaN                  NaN      NaN    NaN   
3                     NaN                  NaN      NaN    NaN   
4                     NaN                  NaN      NaN    NaN   

             admin2            admin1    country_new admin_id  \
0  Snohomish County        Washington  United States     2988   
1               NaN         Khuzestan           Iran       15   
2               NaN               NaN            NaN      NaN   
3  Snohomish County        Washington  United States     2988   
4               NaN  Pays de la Loire         France       12   

  data_moderator_initials travel_history_binary  
0                     NaN                   NaN  
1                     NaN                   NaN  
2                     NaN                   NaN  
3                     NaN                   NaN  
4                     NaN                   NaN  

[5 rows x 34 columns]

Вот так можно инициализировать. Обратите внимание, что в массивах numpy хранятся именно типизированные значения.

In [2]:
arr = np.array([1, 2, 3], dtype=int)
arr

array([1, 2, 3])

In [3]:
arr.dtype

dtype('int64')

Вот так сделать можно...

In [4]:
arr = np.array([1, 2, '3'], dtype=int)
arr

array([1, 2, 3])

А вот так - нельзя.

In [5]:
arr = np.array([1, 2, 'A'], dtype=int)
arr

ValueError: invalid literal for int() with base 10: 'A'

А так всё приведётся к строкам.

In [6]:
arr = np.array([1, 2, 'A'])
arr

array(['1', '2', 'A'], dtype='<U21')

Есть стандартная функция для генерации случайных массивов. (Угадайте, в каком диапазоне будут значения).

In [7]:
arrRand = np.random.rand(5)
arrRand

array([0.68644674, 0.77477164, 0.90288392, 0.41190751, 0.69040293])

Для массивов иначе определены арифметические операции.


In [8]:
arrNp = np.array([1, 2, 3], dtype=int)
arrPy = [1, 2, 3]

In [9]:
arrPy * 2

[1, 2, 3, 1, 2, 3]

In [10]:
arrNp * 2

array([2, 4, 6])

In [11]:
arrPy + 10

TypeError: can only concatenate list (not "int") to list

In [12]:
arrNp + 10

array([11, 12, 13])

In [13]:
arrNp + arrNp

array([2, 4, 6])

In [14]:
arrPy + arrPy

[1, 2, 3, 1, 2, 3]

И такой, уже знакомы по `pandas` пример!

In [15]:
arrNp > 1

array([False,  True,  True])

In [16]:
arrNp[arrNp > 1]

array([2, 3])

`Numpy` написан на `C`, что значительно ускоряет его работу. Эта библиотека интересна не только сама по себе, но и тем, что её используют или корректно с ней интегрированны такие библиотек как `pandas`, `scipy`, `tensorflow` и `matplotlib`. 

Немного полезных методов...

Мы уже познакомились с полем `.shape`. Эту самую форму можно поменять. Создадим двумерный массив нулей размера `m` на `n`.

In [17]:
m = 5
n = 10
arrZeroes = np.zeros(m * n)
arrZeroes

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Обратите внимание, что в качестве аргумента я передал кортеж!

In [18]:
arrZeroes = arrZeroes.reshape((m, n))
arrZeroes

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Впрочем, форму можно было задать и сразу.

In [19]:
arrZeroes = np.zeros((m, n))
arrZeroes

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Можно итерироваться так, как мы привыкли.

In [20]:
for x in arrNp:
    print(x)

1
2
3


Для массивов `numpy` существует куча стандартных математических методов, которых нет для обычных списков.

In [21]:
'''среднее арифметическое'''
arrNp.mean()

2.0

In [22]:
'''среднеквадратическое отклонение (о котором мы уже говорили)'''
arrNp.std()

0.816496580927726

In [23]:
'''не только минимум...'''
arrNp.min()

1

In [24]:
'''... но и его индекс! (для максимума - аналогично)'''
arrNp.argmin()

0

Наконец, массивы могут математически интерпетироваться как уравнения (а ещё как матрицы, вектора, системы уравнений, но это как-нибудь потом) и предоставлять соответствующие методы.

Этим кодом мы по сути задали уравнение $x^2 + 2x -3 = 0$ и решили его.

In [25]:
equation = np.array([1, 2, -3])
np.roots(equation)

array([-3.,  1.])

А код далее - наоборот, по корням получтит многочлен. 

In [26]:
np.poly([-3, 1])

array([ 1.,  2., -3.])

Задания для работы в классе. Нужно сдать до конца пары! Я постарался сделать их не особо сложными, но содержательными.

###Задание 1
Напишите (используя `numpy`) функцию, которая принимает на вход три аргумента и возвращает решение квадратного уравнения с заданными коэффициентами. 

In [44]:
def solveQudraticEquation(a, b, c):
    arr = np.array([a, b, c])
    return np.roots(arr)

In [45]:
solveQudraticEquation(1, 2, -3)

array([-3.,  1.])

###Задание 2
Используя только `np.random.rand(n)` и стандартные арифметические операции сгенерируйте массив случайных чисел от **-1** до **1**. 

**Подсказка:** подумайте, как сделать так, чтобы из чисел от **0** до **1** сделать числа от **0** до **2**. Когда придумаете, поймите, как из чисел от **0** до **2** сделать числа от **-1** до **1**.

In [40]:
myRandomArr = np.random.rand(5) * 2     # 0 - 2
myRandomArr = np.random.rand(5) * 2 - 1 # -1 - 1
myRandomArr

array([-0.57218595,  0.40503179,  0.12331327, -0.27970491,  0.6879641 ])

###Задание 3
Проверьте, что будет, если попытаться решить уравнение, у которого нет действительных корней (отрицательный дискриминант).

Как по этим корням понять, что они не являются действительными.

**Подсказка:** в примерах есть строчка, которая вам поможет. Если никак не получается догадаться, то обратитесь ко мне за добавочной подсказкой.

In [61]:
def rootsAreReal(equationArr):
    return np.roots(equationArr).dtype == np.float64
    

assert rootsAreReal(np.array([1, 2, -3])) == True
assert rootsAreReal(np.array([1, 2, 10])) == False
assert rootsAreReal(np.array([1, 0, 0])) == True

###Задание 4.1
Используя решения предыдущих пунктов сделайте следующее (функцию из пункта 1 использовать не стоит, с ней будет не очень удобно):


1.   Сгенерируйте тысячу случайных массивов из пункта **2**.
2.   Посчитайте, у скольких из них корни являются действительными числами.
3.   Приблизительно вычислите вероятность этого события.



In [80]:
cnt = 0
for i in range(1000):
    arr = np.random.rand(5) * 2 - 1
    if np.roots(arr).dtype == np.float64:
        cnt += 1
        
cnt
# probability = ~40/1000

39

###Задание 4.2
Выполните предыдущее задание так, чтобы результат был по сути аналогичен, но уравнения не хранились в памяти разом, а генерировались по одному.

In [0]:
cnt = 0
for i in range(1000):
    arr = np.random.rand(5) * 2 - 1
    if np.roots(arr).dtype == np.float64:
        cnt += 1
        
cnt

###Задание 5
Исследуйте, как изменится вероятность из предыдушего пункта, если генерировать уравнения как-то иначе (придумайте как минимум два не бессмысленных варианта). Вам доступны любые способы генерации случайных чисел.

In [168]:
cnt = 0
for i in range(1000):
    arr = np.random.rand(5) * 2
    if np.roots(arr).dtype == np.float64:
        cnt += 1
        
cnt
# probability = ~1/1000

0